In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
print(data1)

[0, 1, 2, 3, 4, 5]


In [3]:
a1 = np.array(data1)
print(a1)

[0 1 2 3 4 5]


In [4]:
data2 = [0, 1, 2, 3, 4, 5.5]
a2 = np.array(data2)
print(a2)

[0.  1.  2.  3.  4.  5.5]


In [5]:
print(a1.dtype)

int32


In [6]:
print(a2.dtype)

float64


In [7]:
data3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data3)
a3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a3)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a4 = np.arange(0, 10, 2)
a5 = np.arange(1, 10)
a6 = np.arange(5)

print(a4)
print(a5)
print(a6)

[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [13]:
a7 = np.arange(12).reshape(4, 3)
print(a7)
print('='*20)
print(a7.shape)
# a8 = np.arange(11).reshape(4, 3)
# print(a8)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [14]:
a1 = np.linspace(1, 10, 10)
print(a1)

a2 = np.linspace(1, 10, 8)
print(a2)

a3 = np.linspace(0, np.pi, 20)
print(a3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [15]:
a1 = np.zeros(10, int)
print(a1)
print('-' * 20)
a2 = np.zeros((3, 4), int)
print(a2)
print('-' * 20)
a3 = np.ones(5)
print(a3)
print('-' * 20)
a4 = np.ones((3, 5))
print(a4)
print('-' * 20)
a5 = np.eye(3)
print(a5)

[0 0 0 0 0 0 0 0 0 0]
--------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
--------------------
[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
--------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
np.zeros((3, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
a1 = np.array(['1.567', '0.123', '5.232', '5', '8'])
num = a1.astype(float)
print(a1)
print(num)
print(num.dtype)

['1.567' '0.123' '5.232' '5' '8']
[1.567 0.123 5.232 5.    8.   ]
float64


In [18]:
a1_f = np.array([10, 20, 0.345, 5.87, 9.12])
a1_i= a1_f.astype(int)
print(a1_f)
print(a1_f.dtype)
print(a1_i)
print(a1_i.dtype)

[10.    20.     0.345  5.87   9.12 ]
float64
[10 20  0  5  9]
int32


In [21]:
list01 = [1, 2, 3, 4, 5]
list02 = [10, 20, 30, 40, 50]
print(list01 + list02)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [22]:
a1 = np.array([10, 20, 30, 40])
a2 = np.array([1, 2, 3, 4])
print(a1 + a2)
print(a1 - a2)
print(a1 * 2)
print(a1 ** 2)
print(a1 * a2)
print(a1 / a2)
print(a1 / (a2 ** 2))
print(a1 > 20)

[11 22 33 44]
[ 9 18 27 36]
[20 40 60 80]
[ 100  400  900 1600]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10.          5.          3.33333333  2.5       ]
[False False  True  True]


In [23]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [24]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]
